---
# Instances variables
instances:
- name: ascn-vm-test
  gce_machine_type: e2-micro
  gce_disk_size: 10
  gce_region: europe-west6
  gce_zone: europe-west6-a
  gce_project: ascn-337122
  gce_labels:
    type: testing
