---
# Instances variables
instances:
- name: kubernetes-master
  gce_machine_type: e2-highcpu-8
  gce_disk_size: 20
  gce_region: europe-west1
  gce_zone: europe-west1-b
  gce_project: ascn-337122
  gce_labels:
    type: kubernetes
    kubernetes: master
  gce_status: RUNNING

- name: kubernetes-node-wikijs
  gce_machine_type: e2-highcpu-4
  gce_disk_size: 20
  gce_region: europe-west1
  gce_zone: europe-west1-b
  gce_project: ascn-337122
  gce_labels:
    type: kubernetes
    kubernetes: worker
    node: wikijs
  gce_status: RUNNING

- name: kubernetes-node-postgres
  gce_machine_type: e2-highcpu-4
  gce_disk_size: 20
  gce_region: europe-west1
  gce_zone: europe-west1-b
  gce_project: ascn-337122
  gce_labels:
    type: kubernetes
    kubernetes: worker
    node: postgres
  gce_status: RUNNING
