---
- name: Copy the join command to remote location
  copy:
    src: /tmp/kubernetes-join-command.sh
    dest: /tmp/
    mode: 0777

- name: Join the node to cluster
  shell: sh /tmp/kubernetes-join-command.sh
