---
- name: Resetting kubeadm
  shell: kubeadm reset -f

- name: Initialize Kubernetes Cluster
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16

- name: Create .kube directory
  become: no
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube
    group: kube

- name: Install Pod network
  become: no
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Generate join command
  become: no
  shell: kubeadm token create --print-join-command > /tmp/kubernetes-join-command.sh

- name: Copy join command to local file
  fetch:
    src: /tmp/kubernetes-join-command.sh
    dest: /tmp/
    flat: yes
