---
- name: Initialize Kubernetes Cluster
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address={{ ansible_default_ipv4.address }}"

- name: Create .kube directory
  become: no
  file:
    path: /home/kube/.kube
    state: directory
    mode: 0755

- name: Copy admin.conf to user's kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kube/.kube/config
    remote_src: yes
    owner: kube
    group: kube

- name: Edit kubernetes scheduler deployment file
  lineinfile:
    dest: /etc/kubernetes/manifests/kube-scheduler.yaml
    regexp: '- --port=0'
    state: absent
  notify: restart kubelet

- name: Force Kubelet restart
  meta: flush_handlers

- name: Copy flannel deployment file to master node
  copy:
    src: kube-flannel.yml
    dest: /tmp/

- name: Set master node network interface on flannel deployment file
  lineinfile:
    backrefs: yes
    dest: /tmp/kube-flannel.yml
    regexp: '(^.*--iface=)'
    line: '\1{{ ansible_default_ipv4.interface }}'
    state: present

- name: Install Pod network
  become: no
  shell: kubectl apply -f /tmp/kube-flannel.yml

- name: Generate join command
  become: no
  shell: kubeadm token create --print-join-command > /tmp/kubernetes-join-command.sh

- name: Copy join command to local file
  fetch:
    src: /tmp/kubernetes-join-command.sh
    dest: /tmp/
    flat: yes
