---
- name: Install packages that allow apt to be used over HTTPS
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present
    update_cache: yes

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present

- name: Install Docker and its dependecies
  apt: 
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io
    state: present
    update_cache: yes

- name: Move Docker configuration file to remote
  copy:
    src: daemon.json
    dest: /etc/docker/
  notify:
    - enable docker
    - restart docker

- name: Force Docker restart
  meta: flush_handlers
