---
- name: enable elasticsearch
  service:
    name: elasticsearch
    daemon_reload: yes
    enabled: yes

- name: restart elasticsearch
  service: 
    name: elasticsearch
    state: restarted
  register: elasticsearch_details
  until: elasticsearch_details.status.ActiveState == "active"
  retries: 5
  delay: 60

- name: enable kibana
  service:
    name: kibana
    daemon_reload: yes
    enabled: yes

- name: restart kibana
  service: 
    name: kibana
    state: restarted
  register: kibana_details
  until: kibana_details.status.ActiveState == "active"
  retries: 5
  delay: 60
