---
- name: Clean up configurations from previous cluster
  hosts: label_type_kubernetes
  become: yes
  roles:
    - cleanup_cluster

- name: Setting up Kubernetes on master node
  hosts: label_kubernetes_master
  become: yes
  remote_user: kube
  roles:
    - initialize_cluster

- name: Setting up Kubernetes on worker nodes
  hosts: label_kubernetes_worker
  become: yes
  remote_user: kube
  roles:
    - join_cluster

- name: Label worker nodes
  hosts: label_kubernetes_master
  remote_user: kube
  roles:
    - label_worker_nodes

- name: Deploying Wiki.js on Kubernetes cluster
  hosts: label_kubernetes_master
  become: yes
  remote_user: kube
  roles:
    - deploy_wikijs
