---
- name: Setting up Elasticsearch and Kibana on master node
  hosts: label_kubernetes_master
  become: yes
  roles:
    - setup_monitoring_master

- name: Setting up Metricbeat on worker nodes
  hosts: label_kubernetes_worker
  become: yes
  roles:
    - setup_monitoring_workers

- name: Restart Docker on master node
  hosts: label_kubernetes_master
  become: yes
  tasks:
    - name: Restart Docker
      service:
        name: docker
        state: restarted
