---
- name: enable metricbeat
  service:
    name: metricbeat
    daemon_reload: yes
    enabled: yes

- name: restart metricbeat
  service: 
    name: metricbeat
    state: restarted
  register: metricbeat_details
  until: metricbeat_details.status.ActiveState == "active"
  retries: 5
  delay: 60
